[package]
name = "rust_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.10.2" }
diesel = { version = "2.2.10", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }

