[package]
name = "diesel_demo2"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.10.2" }
diesel = { version = "2.2", features = ["postgres", "r2d2"] }
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
env_logger = "0.11"
serde_json = "1.0"
