[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/Users/nonfan/Projects/Github Projects/diesel-demo/examples/ch08_features_custom_types/migrations"

